package com.motorcycles.factories.enums;

public enum PartsMotorcycle {
    CLASS_MOTORCYCLE,
    BRAND_MOTORCYCLE,
    MOTOR_TYPE,
    LOCATION_CYLINDERS_TYPE,
    DRIVE_TYPE,
    COOLING_TYPE,
    FUEL_SUPPLY_TYPE,
    FRONT_SUSPENSION,
    BACK_SUSPENSION,
    FRONT_SUSPENSION_TYPE,
    BACK_SUSPENSION_TYPE,
    BRAKE_TYPE,
    FRONT_WHEEL,
    BACK_WHEEL
}
